apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app
        image: $DOCKER_USERNAME/weather-app:testing
        ports:
        - containerPort: 8081  # Change container port to 8081


---
apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
spec:
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 8081  # Change service port to 8081
      targetPort: 8081  # Change target port to 8081
  type: NodePort
